package com.tabuk.mykad.model.entity;
// Generated Aug 24, 2009 8:06:58 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
)
public class Student  implements java.io.Serializable {


     private String id;
     private String name;
     private Date dob;
     private String citizenship;
     private String race;
     private String gender;
     private String religion;
     private StudentImage studentImage;

    public Student() {
    }

	
    public Student(String id) {
        this.id = id;
    }
    public Student(String id, String name, Date dob, String citizenship, String race, String gender, String religion, StudentImage studentImage) {
       this.id = id;
       this.name = name;
       this.dob = dob;
       this.citizenship = citizenship;
       this.race = race;
       this.gender = gender;
       this.religion = religion;
       this.studentImage = studentImage;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=12)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name", length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dob", length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="citizenship", length=18)
    public String getCitizenship() {
        return this.citizenship;
    }
    
    public void setCitizenship(String citizenship) {
        this.citizenship = citizenship;
    }

    
    @Column(name="race", length=25)
    public String getRace() {
        return this.race;
    }
    
    public void setRace(String race) {
        this.race = race;
    }

    
    @Column(name="gender", length=1)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="religion", length=50)
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="student")
    public StudentImage getStudentImage() {
        return this.studentImage;
    }
    
    public void setStudentImage(StudentImage studentImage) {
        this.studentImage = studentImage;
    }




}


